### ISSUE TITLE
Fluid color detection

### ISSUE THREAD

**Issue by garudaonekh** [adafruit/Adafruit_AS7341#18]
Hi,
I want to use this chip to detect color of water when I apply some reagent for aquaculture water parameter testing.
For example, measure the Ammonia amount in the fish tank.
Is this chip recommended for this purpose?

**Comment by ladyada** [comment]
might work, no idea :)

**Comment by sgbaird** [comment]
@garudaonekh I've thought about this in the context of detecting color of a liquid - I'm guessing it will probably work for color detection of liquids under normal lighting conditions if you increase the integration time; however, I'm not sure if it will be sensitive enough to measure ammonia concentration in water for your use-case. For that, probably best to use a pH sensor as long as you know what else is in the water. Curious to hear back if you give this a try and how it goes.
