### ISSUE TITLE
sensor_id unused

### ISSUE THREAD

**Issue by jrw429** [adafruit/Adafruit_AS7341#24]
In Adafruit_AS7341::begin() it has a parameter sensor_id which is "The unique ID to differentiate the sensors from others". This is passed to _init(), where it is not used. This generates "warning: unused parameter 'sensor_id'". Not sure if the parameter should be dropped, or if it is a real feature waiting to be implemented.

**Comment by caternuson** [comment]
Looks like a placeholder for potential future use with the Unified Sensor Library:
https://github.com/adafruit/Adafruit_Sensor

Can add a line:
```cpp
(void)sensor_id
```
in `_init` to suppress the compiler warn.

**Comment by jrw429** [comment]
I agree that would be a good way to fix the warning.

**Comment by caternuson** [comment]
Closing. Fixed with #23.
