### ISSUE TITLE
Adafruit_BusIO_Register.h ------- no such file or directory  found

### ISSUE THREAD

**Issue by craziks-creator** [adafruit/Adafruit_AS7341#4]
![Screenshot_2020-08-13-09-02-11-937_com bluino bluinoloaderpro](https://user-images.githubusercontent.com/67502395/90091367-d2f46200-dd43-11ea-9c21-4bc231238cba.jpg)

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_AS7341/blob/master/library.properties#L10
