### ISSUE TITLE
Errors in compiling 

### ISSUE THREAD

**Issue by craziks-creator** [adafruit/Adafruit_AS7341#6]
![Screenshot_2020-08-14-07-38-48-139_com bluino bluinoloaderpro](https://user-images.githubusercontent.com/67502395/90206573-a1da6700-de01-11ea-8d0f-3844cdd976e8.jpg)
![Screenshot_2020-08-14-07-38-43-628_com bluino bluinoloaderpro](https://user-images.githubusercontent.com/67502395/90206576-a56dee00-de01-11ea-8176-2d6ed976989e.jpg)
![Screenshot_2020-08-14-07-38-53-506_com bluino bluinoloaderpro](https://user-images.githubusercontent.com/67502395/90206579-a69f1b00-de01-11ea-99c0-a9ac8bca8b6b.jpg)
![Screenshot_2020-08-14-07-38-50-979_com bluino bluinoloaderpro](https://user-images.githubusercontent.com/67502395/90206581-a868de80-de01-11ea-8e83-62640e08dfdb.jpg)
![Screenshot_2020-08-14-07-38-57-928_com bluino bluinoloaderpro](https://user-images.githubusercontent.com/67502395/90206585-a99a0b80-de01-11ea-9681-23f008b5fae5.jpg)
![Screenshot_2020-08-14-07-38-55-685_com bluino bluinoloaderpro](https://user-images.githubusercontent.com/67502395/90206587-aacb3880-de01-11ea-9360-306310288c6f.jpg)

**Comment by ladyada** [comment]
we only support arduino ide, we dont know what you're using and it doesnt look supported
